// Country flags for the player pop-out.
//
// ESPN serves flags by IOC country code (Slovenia = "slo", not the ISO "svn"),
// so we translate the birthPlace country name the athlete feed returns into that
// code. The names are ESPN's own ("USA", "Slovenia", …); the extra aliases cover
// the handful of forms it varies on. An unmapped country returns null and the
// pop-out shows the name with no flag — a missing entry degrades quietly rather
// than rendering a broken image. Every code here is confirmed against the CDN.
const IOC = {
  USA: 'usa',
  'United States': 'usa',
  Canada: 'can',
  Mexico: 'mex',
  Bahamas: 'bah',
  Jamaica: 'jam',
  Cuba: 'cub',
  Haiti: 'hai',
  'Dominican Republic': 'dom',
  'Puerto Rico': 'pur',
  'US Virgin Islands': 'isv',
  'Trinidad and Tobago': 'tri',
  Panama: 'pan',
  Argentina: 'arg',
  Brazil: 'bra',
  Venezuela: 'ven',
  Colombia: 'col',
  Uruguay: 'uru',
  Chile: 'chi',
  'United Kingdom': 'gbr',
  England: 'gbr',
  Scotland: 'gbr',
  Wales: 'gbr',
  'Great Britain': 'gbr',
  France: 'fra',
  Spain: 'esp',
  Germany: 'ger',
  Italy: 'ita',
  Portugal: 'por',
  Ireland: 'irl',
  Netherlands: 'ned',
  Belgium: 'bel',
  Switzerland: 'sui',
  Austria: 'aut',
  Sweden: 'swe',
  Norway: 'nor',
  Denmark: 'den',
  Finland: 'fin',
  Greece: 'gre',
  Croatia: 'cro',
  Serbia: 'srb',
  Slovenia: 'slo',
  'Bosnia and Herzegovina': 'bih',
  Montenegro: 'mne',
  'North Macedonia': 'mkd',
  Poland: 'pol',
  'Czech Republic': 'cze',
  Czechia: 'cze',
  Lithuania: 'ltu',
  Latvia: 'lat',
  Estonia: 'est',
  Ukraine: 'ukr',
  Russia: 'rus',
  Georgia: 'geo',
  Turkey: 'tur',
  Israel: 'isr',
  Nigeria: 'nga',
  Cameroon: 'cmr',
  Senegal: 'sen',
  'DR Congo': 'cod',
  'Democratic Republic of the Congo': 'cod',
  'Republic of the Congo': 'cgo',
  Congo: 'cgo',
  Angola: 'ang',
  'South Sudan': 'ssd',
  Sudan: 'sud',
  Egypt: 'egy',
  Tunisia: 'tun',
  Morocco: 'mar',
  Mali: 'mli',
  Guinea: 'gui',
  Gabon: 'gab',
  Ghana: 'gha',
  'Ivory Coast': 'civ',
  "Cote d'Ivoire": 'civ',
  'Cape Verde': 'cpv',
  Kenya: 'ken',
  'South Africa': 'rsa',
  'Central African Republic': 'caf',
  Australia: 'aus',
  'New Zealand': 'nzl',
  China: 'chn',
  Japan: 'jpn',
  'South Korea': 'kor',
  Philippines: 'phi',
  'Chinese Taipei': 'tpe',
  Taiwan: 'tpe',
  Iran: 'iri',
  India: 'ind',
  'American Samoa': 'asa',
  Samoa: 'sam',
  Tonga: 'tga',
  Fiji: 'fij',
}

// URL for a country's flag, or null when we have no code for it.
export function flagUrl(country) {
  const code = IOC[country]
  return code ? `https://a.espncdn.com/i/teamlogos/countries/500/${code}.png` : null
}
